# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Wanli Ni
email: charleswall@bupt.edu.cn
description: >- # this means to ignore newlines until "baseurl:"
#Wanli Ni received the B.Eng. and Ph.D. degrees in the School of Information and Communication Engineering from the Beijing University of Posts and Telecommunications, China, in 2018 and 2023, respectively. From September 2020 to June 2022, he was a Visiting Student (remote) with the School of Electronic Engineering and Computer Science, Queen Mary University of London, U.K., under the supervision of Dr. Yuanwei Liu. From July 2022 to September 2022, he was a Visiting Student with the Department of Electrical and Electronic Engineering, Southern University of Science and Technology, Shenzhen, China, under the supervision of Dr. Changsheng You. From December 2022 to May 2023, he was a Visiting Student with the School of Computer Science and Engineering, Nanyang Technological University, Singapore ore, under the supervision of Prof. Dusit Niyato. His research interests include federated learning (FL), reconfigurable intelligent surface (RIS), non-orthogonal multiple access (NOMA), over-the-air computation (AirComp), performance analysis and optimization of wireless networks.
#He was a recipient of the Samsung Scholarship in 2019 and the National Scholarship in 2021 and 2022. He was a co-author of the Best Paper Award in the IEEE SAGC 2020. He was a receipt of the IEEE ComSoc Student Travel Grant from multiple international conferences including IEEE GLOBECOM, INFOCOM, and ICC. He was selected as an Exemplary Reviewer of the IEEE WIRELESS COMMUNICATIONS LETTERS in 2021, the IEEE COMMUNICATIONS LETTERS and IEEE TRANSACTIONS ON COMMUNICATIONS in 2022
#>- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  wanli-ni

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
